name: "Terraform Delete"

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR  

jobs:
  delete:
    name: "delete"
    uses: subhamay-bhattacharyya/9999-reusable-wf/.github/workflows/tf-cicd-destroy.yaml@main
    secrets: 
      aws-region:  ${{ secrets.AWS_REGION }}
      devl-aws-role-arn: ${{ secrets.DEVL_AWS_ROLE_ARN }}
      devl-kms-key-arn:  ${{ secrets.DEVL_AWS_KMS_KEY_ARN }}
      devl-aws-tf-state-bucket-name:  ${{ secrets.DEVL_AWS_TF_STATE_BUCKET_NAME }}
      test-aws-role-arn: ${{ secrets.TEST_AWS_ROLE_ARN }}
      test-kms-key-arn: ${{ secrets.TEST_AWS_KMS_KEY_ARN }}
      test-aws-tf-state-bucket-name:  ${{ secrets.TEST_AWS_TF_STATE_BUCKET_NAME }}
      prod-aws-role-arn: ${{ secrets.PROD_AWS_ROLE_ARN }}
      prod-kms-key-arn: ${{ secrets.PROD_AWS_KMS_KEY_ARN }}
      prod-aws-tf-state-bucket-name:  ${{ secrets.PROD_AWS_TF_STATE_BUCKET_NAME }}